'use client';
import {useState,type ReactNode} from 'react';
import {type PortalData,type Booking,type Exercise,londonDay,londonInput,londonToIso,sessionBalance} from '@/lib/portal/model';
import type {Action} from './Portal';
import {Balance,BookingList,Empty,ExerciseCard,HomeworkGrid,Metrics,Modal,dateTime} from './Shared';
type Dialog={type:'client'|'credit'|'booking'|'exercise'|'homework'|'invite';booking?:Booking;exercise?:Exercise;url?:string};
export default function Admin({data,tab,action,navigate,onError}:{data:PortalData;tab:string;action:Action;navigate:(t:string)=>void;onError:(s:string)=>void}){
 const [search,setSearch]=useState(''),[clientId,setClientId]=useState(''),[dialog,setDialog]=useState<Dialog|null>(null),[formClient,setFormClient]=useState(''),[busy,setBusy]=useState(false),[formError,setFormError]=useState(''),[period,setPeriod]=useState('upcoming');
 const clients=data.clients.filter(c=>c.role==='athlete'),client=clients.find(c=>c.id===clientId),names=Object.fromEntries(data.clients.map(c=>[c.id,c.name]));
 const filtered=clients.filter(c=>`${c.name} ${c.email}`.toLowerCase().includes(search.toLowerCase()));
 const now=Date.parse(data.asOf),upcoming=data.bookings.filter(b=>b.status==='scheduled'&&Date.parse(b.ends_at)>=now).sort((a,b)=>a.starts_at.localeCompare(b.starts_at));
 const credits=data.credits.filter(c=>c.client_id===clientId),bookings=data.bookings.filter(b=>b.client_id===clientId);
 function open(d:Dialog){setDialog(d);setFormClient(d.booking?.client_id||clientId||clients.find(c=>c.active)?.id||'');setFormError('');}
 async function run(body:Record<string,unknown>){try{return await action(body);}catch(e){onError(e instanceof Error?e.message:'Please try again.');return null;}}
 async function invite(id:string){setBusy(true);const r=await run({action:'invite',client_id:id});if(r?.url)open({type:'invite',url:String(r.url)});setBusy(false);}
 function viewClient(id:string){setClientId(id);navigate('clients');}
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy||!dialog)return;setBusy(true);setFormError('');try{
  const values=Object.fromEntries(new FormData(e.currentTarget));const body:Record<string,unknown>={...values,action:dialog.type};
  if(dialog.type==='booking'){body.starts_at=londonToIso(String(values.starts_at));body.ends_at=londonToIso(String(values.ends_at));if(dialog.booking)body.id=dialog.booking.id;}
  if(dialog.type==='exercise'&&dialog.exercise)body.id=dialog.exercise.id;
  const result=await action(body);if(dialog.type==='client'&&result.id)setClientId(String(result.id));setDialog(null);
 }catch(e){setFormError(e instanceof Error?e.message:'Could not save.');}finally{setBusy(false);}}
 const selectClient=<label>Client<select name="client_id" required value={formClient} onChange={e=>setFormClient(e.target.value)}><option value="" disabled>Select a client</option>{clients.filter(c=>c.active).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>;
 const field=(title:string,name:string,options:{type?:string;value?:string|number;required?:boolean;placeholder?:string;min?:number;max?:number}={})=><label>{title}<input name={name} type={options.type||'text'} defaultValue={options.value} required={options.required!==false} placeholder={options.placeholder} min={options.min} max={options.max}/></label>;
 const modal=dialog&&<Modal title={{client:'Add a client',credit:'Add session credits',booking:dialog.booking?'Edit booking':'Add a booking',exercise:dialog.exercise?'Edit exercise':'Add an exercise',homework:'Assign homework',invite:'Private access link'}[dialog.type]} onClose={()=>{if(!busy)setDialog(null);}}>{dialog.type==='invite'?<><p>Share this link privately with the client. It expires after seven days and can be used once. Creating a new link replaces any earlier unused link.</p><input className="p-invite-url" value={dialog.url} readOnly aria-label="Private invitation link" onFocus={e=>e.target.select()}/><button className="p-button" onClick={async()=>{try{await navigator.clipboard.writeText(dialog.url||'');setFormError('Link copied.');}catch{setFormError('Select and copy the link above.');}}}>Copy access link ↗</button>{formError&&<p role="status">{formError}</p>}<p className="p-muted p-small">No email has been sent automatically.</p></>:<form className="p-form" onSubmit={submit}>
  {dialog.type==='client'&&<>{field('Full name','name')}{field('Email address','email',{type:'email'})}<p className="p-muted p-small">You can create a private access link after adding the client.</p></>}
  {dialog.type==='credit'&&<>{selectClient}{field('Pack or plan name','label',{placeholder:'e.g. October · 8 sessions'})}<div className="p-form-pair">{field('Number of sessions','quantity',{type:'number',min:1,max:500,value:4})}{field('Available from','starts_on',{type:'date',value:londonDay()})}</div>{field('Expiry date (optional)','expires_on',{type:'date',required:false})}{field('Payment reference (optional)','source_reference',{required:false,placeholder:'Helps prevent adding the same purchase twice'})}<p className="p-muted p-small">For an opening balance, enter the sessions still owed and only add bookings that have not already been deducted. Recurring plans need a new allocation each month.</p></>}
  {dialog.type==='booking'&&<>{selectClient}<label>Session pack<select name="credit_id" defaultValue={dialog.booking?.credit_id||''}><option value="">No charge / consultation</option>{data.credits.filter(c=>c.client_id===formClient).map(c=><option value={c.id} key={c.id}>{c.label} · {Math.max(0,c.quantity-data.bookings.filter(b=>b.credit_id===c.id&&b.status!=='cancelled').length)} unbooked</option>)}</select></label>{field('Session title','title',{value:dialog.booking?.title||'Coaching session'})}<div className="p-form-pair">{field('Starts · London time','starts_at',{type:'datetime-local',value:dialog.booking?londonInput(dialog.booking.starts_at):undefined})}{field('Ends · London time','ends_at',{type:'datetime-local',value:dialog.booking?londonInput(dialog.booking.ends_at):undefined})}</div>{field('Location or meeting details','location',{value:dialog.booking?.location||'London'})}<label>Note for the client<textarea name="notes" rows={3} maxLength={2000} defaultValue={dialog.booking?.notes||''}/></label><p className="p-muted p-small">A booked session reserves a credit. Completed and chargeable missed sessions use it; cancelling releases it.</p></>}
  {dialog.type==='exercise'&&<>{field('Exercise name','title',{value:dialog.exercise?.title})}{field('Category','category',{value:dialog.exercise?.category||'Movement'})}{field('YouTube video link','video',{type:'url',value:dialog.exercise?`https://www.youtube.com/watch?v=${dialog.exercise.youtube_id}`:undefined,placeholder:'https://www.youtube.com/watch?v=…'})}<label>Coaching cues<textarea name="cues" rows={4} maxLength={4000} defaultValue={dialog.exercise?.cues||''}/></label><p className="p-muted p-small">Public or unlisted videos with embedding enabled work here.</p></>}
  {dialog.type==='homework'&&<>{selectClient}<label>Exercise<select name="exercise_id" required defaultValue=""><option value="" disabled>Select an exercise</option>{data.exercises.filter(e=>e.active).map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select></label>{field('Prescription','prescription',{placeholder:'e.g. 3 sets of 6, three days per week'})}<label>Individual instruction<textarea name="coach_note" rows={3} maxLength={2000}/></label></>}
  {formError&&<p className="p-error" role="alert">{formError}</p>}<button className="p-button" disabled={busy}>{busy?'Saving…':'Save'} ↗</button></form>}</Modal>;
 const heading=(title:string,description:string,buttons?:ReactNode)=><header className="p-page-heading"><p className="p-kicker">CG PERFORMANCE / COACH WORKSPACE</p><div className="p-heading-row"><div><h1>{title}</h1><p>{description}</p></div>{buttons&&<div className="p-heading-actions">{buttons}</div>}</div></header>;
 const clientTable=<section className="p-panel p-client-list">{filtered.length?filtered.map(c=>{const balance=sessionBalance(data.credits.filter(p=>p.client_id===c.id),data.bookings.filter(b=>b.client_id===c.id));return <button className="p-client-row" key={c.id} onClick={()=>viewClient(c.id)}><span className="p-avatar">{c.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</span><span className="p-client-name"><strong>{c.name}</strong><small>{c.email}</small></span><span className="p-client-credit"><strong>{balance.remaining}</strong><small>sessions left</small></span><span className={`p-badge ${c.active?'completed':''}`}>{c.active?c.user_id?'Active':'Not activated':'Paused'}</span><span aria-hidden="true">↗</span></button>;}):<Empty title="Add your first client">Create their profile, enter their current session balance, then share a private access link.</Empty>}</section>;
 let content:ReactNode;
 if(tab==='clients'&&client){const currentConnections=data.connections.filter(c=>c.client_id===client.id&&c.status==='connected');const source=currentConnections[0];content=<><button className="p-link p-back" onClick={()=>setClientId('')}>← All clients</button>{heading(client.name,client.email,<><button className="p-button p-secondary" onClick={()=>invite(client.id)} disabled={busy}>Create access link</button><button className="p-button" onClick={()=>open({type:'credit'})}>Add sessions +</button></>)}<Balance credits={credits} bookings={bookings}/><div className="p-section-head"><h2>Bookings</h2><button className="p-link" onClick={()=>open({type:'booking'})}>Add booking +</button></div><section className="p-panel"><BookingList items={[...bookings].sort((a,b)=>b.starts_at.localeCompare(a.starts_at))} admin onEdit={booking=>open({type:'booking',booking})} onStatus={(id,status)=>{void run({action:'booking-status',id,status});}}/></section><div className="p-section-head"><h2>Homework</h2><button className="p-link" onClick={()=>open({type:'homework'})}>Assign exercise +</button></div><HomeworkGrid assignments={data.homework.filter(h=>h.client_id===client.id)} exercises={data.exercises} logs={data.logs.filter(l=>l.client_id===client.id)} onArchive={id=>{void run({action:'archive-homework',id});}}/><div className="p-section-head"><h2>{source?`${source.provider} · Latest readings`:'Wearable data'}</h2><button className="p-link" onClick={()=>navigate('wearables')}>View all data ↗</button></div><Metrics metrics={data.metrics.filter(m=>m.connection_id===source?.id)}/><section className="p-panel p-pack-list"><h2>Session allocations</h2>{credits.map(c=><div className="p-pack" key={c.id}><div><h3>{c.label}</h3><p>From {c.starts_on}{c.expires_on?` · Expires ${c.expires_on}`:''}</p></div><span>{c.quantity} sessions</span></div>)}</section><section className="p-panel"><h2>Account access</h2><p>{client.active?'Pausing a client blocks their portal access. Their records are retained.':'This client is paused and cannot access the portal.'}</p><button className="p-link" onClick={()=>{if(window.confirm(`${client.active?'Pause':'Restore'} ${client.name}’s portal access?`))void run({action:'client-active',client_id:client.id,active:!client.active});}}>{client.active?'Pause access':'Restore access'}</button></section></>;}
 else if(tab==='clients'){content=<>{heading('Your clients.','A clear view of each client’s sessions, homework and shared data.',<button className="p-button" onClick={()=>open({type:'client'})}>Add client +</button>)}<label className="p-search"><span className="p-sr-only">Search clients</span><input placeholder="Search by name or email…" value={search} onChange={e=>setSearch(e.target.value)}/></label>{clientTable}</>;}
 else if(tab==='bookings'){const visible=period==='upcoming'?upcoming:period==='history'?data.bookings.filter(b=>b.status!=='scheduled'||Date.parse(b.ends_at)<now):data.bookings;content=<>{heading('The diary.','Confirmed sessions and attendance. All times are shown in London time.',<button className="p-button" onClick={()=>open({type:'booking'})} disabled={!clients.some(c=>c.active)}>Add booking +</button>)}<div className="p-section-head"><div className="p-tabs">{['upcoming','history','all'].map(p=><button key={p} aria-pressed={period===p} onClick={()=>setPeriod(p)}>{p[0].toUpperCase()+p.slice(1)}</button>)}</div><select aria-label="Filter by client" value={clientId} onChange={e=>setClientId(e.target.value)}><option value="">All clients</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><section className="p-panel"><BookingList items={visible.filter(b=>!clientId||b.client_id===clientId)} names={names} admin onEdit={booking=>open({type:'booking',booking})} onStatus={(id,status)=>{void run({action:'booking-status',id,status});}}/></section></>;}
 else if(tab==='exercises'){const visible=data.exercises.filter(e=>`${e.title} ${e.category}`.toLowerCase().includes(search.toLowerCase()));content=<>{heading('The exercise library.','Add your YouTube demonstrations, then assign the right work to each client.',<><button className="p-button p-secondary" onClick={()=>open({type:'homework'})} disabled={!clients.length||!data.exercises.length}>Assign homework</button><button className="p-button" onClick={()=>open({type:'exercise'})}>Add exercise +</button></>)}<label className="p-search"><span className="p-sr-only">Search exercises</span><input placeholder="Search exercises or categories…" value={search} onChange={e=>setSearch(e.target.value)}/></label>{visible.length?<div className="p-exercise-grid">{visible.map(e=><ExerciseCard key={e.id} exercise={e} adminAction={<button className="p-link p-archive" onClick={()=>open({type:'exercise',exercise:e})}>Edit exercise ↗</button>}/>)}</div>:<Empty title="Start with one useful demonstration">Paste a public or unlisted YouTube video, add the exercise name and your coaching cues. You can add your channel link in Settings.</Empty>}</>;}
 else if(tab==='wearables'){const ids=new Set(clients.filter(c=>!clientId||c.id===clientId).map(c=>c.id));const connections=data.connections.filter(c=>ids.has(c.client_id)&&c.status!=='revoked');content=<>{heading('The daily picture.','Review the data each client has chosen to share. Readings are kept separate by device.')}<div className="p-section-head"><h2>Connected clients</h2><select aria-label="Filter wearable data by client" value={clientId} onChange={e=>setClientId(e.target.value)}><option value="">All clients</option>{clients.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></div>{!data.wearablesReady&&<div className="p-info">Live syncing needs the Terra integration account and credentials. The portal and client permissions are ready; see Settings for the remaining setup.</div>}{connections.length?connections.map(c=><section className="p-panel" key={c.id}><div className="p-section-head"><div><h2>{names[c.client_id]}</h2><p className="p-muted">{c.provider} · {c.status} · {c.synced_at?`Last received ${dateTime(c.synced_at)}`:'Waiting for first data'}</p></div><button className="p-link" onClick={()=>viewClient(c.client_id)}>Client profile ↗</button></div><Metrics metrics={data.metrics.filter(m=>m.connection_id===c.id)}/><details className="p-history"><summary>Recent readings</summary><div className="p-table-wrap"><table><thead><tr><th>Day</th><th>Type</th><th>Steps</th><th>Sleep</th><th>RMSSD</th><th>SDNN</th></tr></thead><tbody>{data.metrics.filter(m=>m.connection_id===c.id).slice(0,60).map(m=><tr key={`${m.kind}-${m.source_id}`}><td>{m.day}</td><td>{m.kind}</td><td>{m.steps??'—'}</td><td>{m.sleep_seconds===null?'—':`${(m.sleep_seconds/3600).toFixed(1)} h`}</td><td>{m.hrv_rmssd===null?'—':`${m.hrv_rmssd} ms`}</td><td>{m.hrv_sdnn===null?'—':`${m.hrv_sdnn} ms`}</td></tr>)}</tbody></table></div></details></section>):<Empty title="No devices connected yet">Clients connect their own accounts and explicitly choose to share their sleep, steps and HRV with you.</Empty>}</>;}
 else if(tab==='settings'){content=<>{heading('Keep it simple.','Your exercise channel and connection settings.')}<section className="p-panel"><h2>YouTube channel</h2><p className="p-muted">Add your channel link when it’s ready. Videos are added to the exercise library individually so you control the names, cues and client assignments.</p><form className="p-form" onSubmit={async e=>{e.preventDefault();setBusy(true);const values=new FormData(e.currentTarget);await run({action:'channel',url:values.get('url')});setBusy(false);}}>{field('Channel link','url',{type:'url',value:data.youtubeChannel,required:false,placeholder:'https://www.youtube.com/@yourchannel'})}<button className="p-button" disabled={busy}>Save channel ↗</button></form></section><section className="p-panel"><div className="p-row"><h2>Wearable integration</h2><span className={`p-badge ${data.wearablesReady?'completed':''}`}>{data.wearablesReady?'Configured':'Setup needed'}</span></div><p>Garmin, WHOOP, Oura Ring and other supported devices connect through Terra. A Terra account and the relevant provider access are needed before clients can connect. No paid account has been started.</p><ol className="p-setup-list"><li>Set up a Terra account and enable the providers you need.</li><li>Add its API key, developer ID and webhook signing secret to the CGP project’s environment settings.</li><li>Set the webhook destination to <code>https://cgp-dvotion.vercel.app/api/webhooks/terra</code> and enable auth, daily, sleep, reauth and revocation events.</li><li>Redeploy and complete a test connection before inviting clients to sync.</li></ol><p className="p-muted p-small">Required settings: TERRA_API_KEY, TERRA_DEV_ID and TERRA_SIGNING_SECRET. The private database ingest key is provisioned separately. Apple Health and Android Health Connect need a mobile app connection and are not included in this web portal.</p><a className="p-link" href="https://dashboard.tryterra.co" target="_blank" rel="noopener noreferrer">Open Terra ↗</a></section><section className="p-panel"><h2>Starting balances & bookings</h2><p>Add each client’s current session balance before adding their upcoming bookings. Historical records and existing calendars have not been imported. Completed or chargeable missed sessions use one credit; cancelled sessions do not. New monthly allocations are added manually.</p></section></>;}
 else{const low=clients.filter(c=>c.active&&sessionBalance(data.credits.filter(p=>p.client_id===c.id),data.bookings.filter(b=>b.client_id===c.id)).available<=2);content=<>{heading('Your coaching day.','Clients, sessions and the work ahead.',<><button className="p-button p-secondary" onClick={()=>open({type:'client'})}>Add client +</button><button className="p-button" onClick={()=>open({type:'booking'})} disabled={!clients.some(c=>c.active)}>Add booking +</button></>)}<div className="p-admin-stats"><div><span>Active clients</span><strong>{clients.filter(c=>c.active).length}</strong></div><div><span>Next 7 days</span><strong>{upcoming.filter(b=>Date.parse(b.starts_at)<now+7*86400000).length}</strong></div><div><span>Low available balance</span><strong>{low.length}</strong></div><div><span>Connected devices</span><strong>{data.connections.filter(c=>c.status==='connected').length}</strong></div></div><div className="p-section-head"><h2>Coming up</h2><button className="p-link" onClick={()=>navigate('bookings')}>Open diary ↗</button></div><section className="p-panel"><BookingList items={upcoming.slice(0,6)} names={names} admin onEdit={booking=>open({type:'booking',booking})} onStatus={(id,status)=>{void run({action:'booking-status',id,status});}}/></section><div className="p-section-head"><h2>{clients.length?'Clients to check in with':'Your client list starts here'}</h2><button className="p-link" onClick={()=>navigate('clients')}>All clients ↗</button></div>{clients.length?<section className="p-panel">{low.length?low.map(c=><button className="p-checkin-row" key={c.id} onClick={()=>viewClient(c.id)}><strong>{c.name}</strong><span>{sessionBalance(data.credits.filter(p=>p.client_id===c.id),data.bookings.filter(b=>b.client_id===c.id)).available} unbooked sessions</span><span>↗</span></button>):<p className="p-muted">All active clients have more than two unbooked sessions available.</p>}</section>:clientTable}</>;}
 return <>{content}{modal}</>;
}
