'use client';
import {useState} from 'react';
import type {PortalData} from '@/lib/portal/model';
import type {Action} from './Portal';
import {Balance,BookingList,Empty,ExerciseCard,HomeworkGrid,Metrics,dateTime} from './Shared';
export default function Athlete({data,tab,action,navigate,onError}:{data:PortalData;tab:string;action:Action;navigate:(tab:string)=>void;onError:(error:string)=>void}){
 const [library,setLibrary]=useState(false),[search,setSearch]=useState(''),[period,setPeriod]=useState('upcoming'),[consent,setConsent]=useState(false),[busy,setBusy]=useState(''),[source,setSource]=useState('');
 const id=data.profile.id,bookings=data.bookings.filter(b=>b.client_id===id),credits=data.credits.filter(c=>c.client_id===id),homework=data.homework.filter(h=>h.client_id===id),connections=data.connections.filter(c=>c.client_id===id&&c.status!=='revoked');
 const live=connections.filter(c=>c.status==='connected');const selected=live.find(c=>c.id===source)||live[0];const metrics=data.metrics.filter(m=>m.connection_id===selected?.id);
 const upcoming=bookings.filter(b=>b.status==='scheduled'&&Date.parse(b.ends_at)>=Date.parse(data.asOf)).sort((a,b)=>a.starts_at.localeCompare(b.starts_at));
 async function run(body:Record<string,unknown>,endpoint?:string){try{return await action(body,endpoint);}catch(e){onError(e instanceof Error?e.message:'Please try again.');}}
 async function connect(provider:string){setBusy(provider);try{const r=await action({action:'connect',provider,consent},'/api/portal/wearables');if(typeof r.url==='string')window.location.assign(r.url);}catch(e){onError(e instanceof Error?e.message:'Unable to connect.');}finally{setBusy('');}}
 const header=(title:string,subtitle:string)=><header className="p-page-heading"><p className="p-kicker">CG PERFORMANCE / {tab.toUpperCase()}</p><h1>{title}</h1><p>{subtitle}</p></header>;
 if(tab==='bookings')return <>{header('Your sessions.','Every booking and your remaining session balance. Times are shown in London time.')}<Balance credits={credits} bookings={bookings}/><div className="p-section-head"><div className="p-tabs">{['upcoming','history','all'].map(p=><button key={p} aria-pressed={period===p} onClick={()=>setPeriod(p)}>{p[0].toUpperCase()+p.slice(1)}</button>)}</div><a className="p-link" href="mailto:chrisgkoufas.performance@gmail.com">Arrange a session ↗</a></div><section className="p-panel"><BookingList items={period==='upcoming'?upcoming:period==='history'?bookings.filter(b=>b.status!=='scheduled'||Date.parse(b.ends_at)<Date.parse(data.asOf)):[...bookings].sort((a,b)=>b.starts_at.localeCompare(a.starts_at))}/></section><section className="p-panel p-pack-list"><h2>Session packs</h2>{credits.length?credits.map(c=><div className="p-pack" key={c.id}><div><h3>{c.label}</h3><p>{c.quantity} sessions · From {c.starts_on}{c.expires_on?` · Expires ${c.expires_on}`:''}</p></div><span>{bookings.filter(b=>b.credit_id===c.id&&['completed','no_show'].includes(b.status)).length} used</span></div>):<p className="p-muted">Your session packs will appear here once added by Chris.</p>}</section></>;
 if(tab==='homework')return <>{header('Keep the work going.','Your exercises, demonstrations and individual instructions.')}<div className="p-section-head"><div className="p-tabs"><button aria-pressed={!library} onClick={()=>setLibrary(false)}>My homework</button><button aria-pressed={library} onClick={()=>setLibrary(true)}>Exercise library</button></div>{data.youtubeChannel&&<a className="p-link" href={data.youtubeChannel} target="_blank" rel="noopener noreferrer">YouTube channel ↗</a>}</div>{library?<><label className="p-search"><span className="p-sr-only">Search exercise library</span><input placeholder="Search exercises or categories…" value={search} onChange={e=>setSearch(e.target.value)}/></label>{data.exercises.some(e=>e.active)?<div className="p-exercise-grid">{data.exercises.filter(e=>e.active&&`${e.title} ${e.category}`.toLowerCase().includes(search.toLowerCase())).map(e=><ExerciseCard key={e.id} exercise={e}/>)}</div>:<Empty title="The exercise library is on its way">Your coach will add demonstrations here. Your prescribed exercises will be listed under My homework.</Empty>}</>:<HomeworkGrid assignments={homework} exercises={data.exercises} logs={data.logs} onDone={(homework_id,done)=>{void run({action:'homework-done',homework_id,done});}}/>}</>;
 if(tab==='wearables')return <>{header('A little more context.','Connect the device you already use. You choose what to share with Chris.')}<div className="p-section-head"><h2>Your latest readings</h2>{live.length>0&&<select aria-label="Wearable data source" value={selected?.id||''} onChange={e=>setSource(e.target.value)}>{live.map(c=><option key={c.id} value={c.id}>{c.provider}</option>)}</select>}</div><Metrics metrics={metrics}/>{selected&&<p className="p-muted p-small">Source: {selected.provider}. Last received: {selected.synced_at?dateTime(selected.synced_at):'Waiting for the first sync'}. Values depend on what your device supplies.</p>}<section className="p-panel"><h2>Your connections</h2>{!data.wearablesReady&&<div className="p-info">Device connections are being set up. This section will become available once Chris activates wearable syncing.</div>}<label className="p-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>I agree to share my sleep, daily steps, heart rate and HRV with Chris through the wearable connection service for coaching. This is optional. I can disconnect and delete the stored readings at any time.</span></label><div className="p-device-grid">{data.providers.map(provider=>{const c=connections.find(c=>c.provider===provider);return <article className="p-device" key={provider}><div className="p-row"><h3>{provider==='OURA'?'Oura Ring':provider}</h3><span className={`p-badge ${c?.status==='connected'?'completed':''}`}>{c?.status==='connected'?'Connected':c?.status==='pending'?'Awaiting permission':c?.status==='error'?'Reconnect needed':'Not connected'}</span></div><p>Sleep, activity and recovery data where available.</p>{c?<button className="p-link" onClick={()=>{if(window.confirm('Disconnect this device and delete its stored readings from CGP?'))void run({action:'disconnect',id:c.id},'/api/portal/wearables');}}>Disconnect & delete data</button>:<button className="p-button p-secondary" disabled={!data.wearablesReady||!consent||Boolean(busy)} onClick={()=>connect(provider)}>{busy===provider?'Opening…':data.wearablesReady?'Connect device':'Awaiting setup'} ↗</button>}</article>;})}</div></section>{metrics.length>0&&<section className="p-panel"><h2>Recent readings</h2><p className="p-muted">Last 30 days. Different devices may report HRV differently; RMSSD and SDNN are shown separately.</p><div className="p-table-wrap"><table><thead><tr><th>Date</th><th>Source</th><th>Steps</th><th>Sleep</th><th>HRV · RMSSD</th><th>HRV · SDNN</th></tr></thead><tbody>{metrics.slice(0,60).map(m=><tr key={`${m.kind}-${m.source_id}`}><td>{m.day}</td><td>{m.kind}</td><td>{m.steps?.toLocaleString()??'—'}</td><td>{m.sleep_seconds===null?'—':`${(m.sleep_seconds/3600).toFixed(1)} h`}</td><td>{m.hrv_rmssd===null?'—':`${m.hrv_rmssd} ms`}</td><td>{m.hrv_sdnn===null?'—':`${m.hrv_sdnn} ms`}</td></tr>)}</tbody></table></div></section>}</>;
 return <>{header(`Hello, ${data.profile.name.split(' ')[0]}.`,'Everything you need for your next step.')}<div className="p-overview-grid"><Balance credits={credits} bookings={bookings}/><section className="p-next-session"><span className="p-kicker">NEXT SESSION</span>{upcoming[0]?<><h2>{dateTime(upcoming[0].starts_at)}</h2><p>{upcoming[0].title}</p><p>{upcoming[0].location}</p><button className="p-link" onClick={()=>navigate('bookings')}>View your bookings ↗</button></>:<><h2>Let’s get your next<br/>session in the diary.</h2><p>No upcoming booking has been added yet.</p><a className="p-link" href="mailto:chrisgkoufas.performance@gmail.com">Contact Chris ↗</a></>}</section></div><div className="p-section-head"><h2>Your homework</h2><button className="p-link" onClick={()=>navigate('homework')}>View all ↗</button></div><HomeworkGrid assignments={homework.filter(h=>h.active).slice(0,2)} exercises={data.exercises} logs={data.logs} onDone={(homework_id,done)=>{void run({action:'homework-done',homework_id,done});}}/><div className="p-section-head"><h2>{selected?`${selected.provider} · Latest readings`:'Your daily picture'}</h2><button className="p-link" onClick={()=>navigate('wearables')}>{selected?'View wearables':'Connect a device'} ↗</button></div><Metrics metrics={metrics}/></>;
}
