'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import type {PortalData} from '@/lib/portal/model';
import {Icon,Empty} from './Shared';
import Athlete from './Athlete';
import Admin from './Admin';
export type Action=(body:Record<string,unknown>,endpoint?:string)=>Promise<Record<string,unknown>>;
export default function Portal({admin=false}:{admin?:boolean}){
 const [data,setData]=useState<PortalData|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [tab,setTab]=useState('overview'),[invite,setInvite]=useState(''),[inviteInfo,setInviteInfo]=useState<{name:string;email:string;existing:boolean}|null>(null),[mode,setMode]=useState('login'),[busy,setBusy]=useState(false);
 const [email,setEmail]=useState(''),[password,setPassword]=useState('');const noticeTimer=useRef<ReturnType<typeof setTimeout>|null>(null);const invitationRef=useRef<string|null>(null);
 const load=useCallback(async()=>{const r=await fetch('/api/portal',{cache:'no-store'});const value=await r.json();if(r.ok){setData(value);setError('');return true;}if(r.status!==401)setError(value.error||'The portal could not be loaded.');setData(null);return false;},[]);
 useEffect(()=>{let alive=true;const token=invitationRef.current||new URLSearchParams(window.location.hash.slice(1)).get('invite');invitationRef.current=token;const requested=new URLSearchParams(window.location.search).get('tab');
  if(token)window.history.replaceState(null,'',window.location.pathname+window.location.search);
  async function open(){try{
   const [,info]=await Promise.all([load(),token?fetch('/api/portal/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'invite-info',invite:token})}).then(r=>r.json()):null]);
   if(!alive)return;if(requested)setTab(requested);if(token)setInvite(token);
   if(info){if(info.error)setError(info.error);else{setInviteInfo(info);setEmail(info.email);setMode(info.existing?'reset':'register');}}
  }catch{if(alive)setError('Unable to connect. Please try again.');}finally{if(alive)setLoading(false);}}
  void open();return()=>{alive=false;if(noticeTimer.current)clearTimeout(noticeTimer.current);};
 },[load]);
 const signedIn=Boolean(data);
 useEffect(()=>{if(!signedIn)return;const refresh=()=>{if(document.visibilityState==='visible')void load().catch(()=>{});};window.addEventListener('focus',refresh);const timer=setInterval(refresh,60000);return()=>{window.removeEventListener('focus',refresh);clearInterval(timer);};},[signedIn,load]);
 const action:Action=async(body,endpoint='/api/portal')=>{setError('');const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await r.json();if(!r.ok){if(r.status===401)setData(null);throw new Error(result.error||'This could not be saved.');}await load();setNotice(String(result.message||'Saved.'));if(noticeTimer.current)clearTimeout(noticeTimer.current);noticeTimer.current=setTimeout(()=>setNotice(''),4500);return result;};
 async function signIn(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const r=await fetch('/api/portal/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:mode,email,password,invite})});const result=await r.json();if(!r.ok)throw new Error(result.error);setPassword('');setInvite('');setInviteInfo(null);await load();}catch(e){setError(e instanceof Error?e.message:'Please try again.');}finally{setBusy(false);}}
 async function logout(){setBusy(true);try{await fetch('/api/portal/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout'})});setData(null);setError('');}finally{setBusy(false);}}
 function navigate(value:string){setTab(value);window.history.replaceState(null,'',`${window.location.pathname}?tab=${value}`);setError('');}
 if(loading)return <div className="portal-app p-loading"><span className="p-brand">cgp<span>.</span></span><p>Opening your portal…</p></div>;
 if(!data||inviteInfo)return <div className="portal-app p-login-page"><header className="p-login-header"><Link className="p-brand" href="/">cgp<span>.</span></Link><span>{admin?'COACH WORKSPACE':'ATHLETE PORTAL'}</span></header><div className="p-login-grid"><div className="p-login-intro"><p className="p-kicker">YOUR TRAINING, TOGETHER.</p><h1>A clear view.<br/><span>Your next step.</span></h1><p>Your sessions, your homework and the small details that help us keep moving forward.</p><div className="p-login-features"><span><Icon name="bookings"/>Every session, in one place</span><span><Icon name="homework"/>Your exercises and instructions</span><span><Icon name="wearables"/>The data you choose to share</span></div></div><section className="p-login-card"><p className="p-kicker">{inviteInfo?'YOUR PRIVATE INVITATION':'WELCOME BACK'}</p><h2>{inviteInfo?`Hello, ${inviteInfo.name.split(' ')[0]}.`:admin?'Sign in to manage.':'Good to see you.'}</h2><p>{mode==='register'?'Choose a password to activate your portal. Your private link confirms your invitation.':mode==='reset'?'Choose a new password to restore access to your existing account.':'Sign in with your coaching account.'}</p><form onSubmit={signIn} className="p-form"><label>Email address<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="email" readOnly={Boolean(inviteInfo)}/></label><label>{mode!=='login'?'Create a password':'Password'}<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required minLength={mode!=='login'?12:1} maxLength={128} autoComplete={mode!=='login'?'new-password':'current-password'}/></label>{mode!=='login'&&<small>At least 12 characters.</small>}{error&&<p className="p-error" role="alert">{error}</p>}<button className="p-button" disabled={busy}>{busy?'Please wait…':mode==='register'?'Activate my portal':mode==='reset'?'Save password & sign in':'Sign in'} <span>↗</span></button></form>{inviteInfo&&<button className="p-link" onClick={()=>setMode(mode==='login'?(inviteInfo.existing?'reset':'register'):'login')}>{mode==='login'?(inviteInfo.existing?'Reset my password':'Create my account'):'Use my existing password'}</button>}<p className="p-login-help">Need access or help signing in? <a href="mailto:chrisgkoufas.performance@gmail.com">Contact Chris</a>.</p><a className="p-link" href="/privacy">Privacy</a></section></div></div>;
 if(admin&&data.profile.role!=='admin')return <div className="portal-app p-denied"><Empty title="This area is for your coach">Your own sessions and homework are in the athlete portal.</Empty><a className="p-button" href="/portal">Open my portal ↗</a></div>;
 const isAdmin=admin&&data.profile.role==='admin';const tabs=isAdmin?['overview','clients','bookings','exercises','wearables','settings']:['overview','bookings','homework','wearables'];const active=tabs.includes(tab)?tab:'overview';
 return <div className="portal-app p-workspace"><aside className="p-sidebar"><Link href="/" className="p-brand">cgp<span>.</span></Link><span className="p-workspace-label">{isAdmin?'COACH WORKSPACE':'ATHLETE PORTAL'}</span><nav aria-label="Portal sections">{tabs.map(t=><button key={t} className={active===t?'active':''} aria-current={active===t?'page':undefined} onClick={()=>navigate(t)}><Icon name={t}/><span>{t==='homework'?'Homework':t[0].toUpperCase()+t.slice(1)}</span></button>)}</nav><div className="p-sidebar-bottom"><div className="p-profile"><span>{data.profile.name.split(' ').map(w=>w[0]).slice(0,2).join('')}</span><div><strong>{data.profile.name}</strong><small>{isAdmin?'Your clients. Your coaching.':'Coached by Chris Gkoufas'}</small></div></div>{data.profile.role==='admin'&&<a className="p-switch" href={isAdmin?'/portal':'/admin'}>{isAdmin?'Athlete view':'Open admin'} ↗</a>}<button onClick={logout} disabled={busy}><Icon name="logout"/>Sign out</button></div></aside><section className="p-main" aria-label="Coaching workspace"><div className="p-mobile-top"><Link className="p-brand" href="/">cgp<span>.</span></Link><span>{data.profile.role==='admin'?<a href={isAdmin?'/portal':'/admin'}>{isAdmin?'Athlete view ↗':'Open admin ↗'}</a>:data.profile.name.split(' ')[0]}</span><button onClick={logout} aria-label="Sign out"><Icon name="logout"/></button></div>{error&&<div className="p-error" role="alert">{error}</div>}{notice&&<div className="p-toast" role="status">✓ {notice}</div>}{isAdmin?<Admin data={data} tab={active} action={action} navigate={navigate} onError={setError}/>:<Athlete data={data} tab={active} action={action} navigate={navigate} onError={setError}/>}<footer className="p-footnote">CG Performance <span>·</span> Private coaching workspace <a href="/privacy">Privacy</a></footer></section></div>;
}
