import Image from "next/image";
import EnquiryForm from "@/components/EnquiryForm";

export default function Home() {
  return <>
    <section className="hero wrap" aria-labelledby="hero-title">
      <div className="hero-intro"><p className="eyebrow"><span className="status-dot" /> INDIVIDUAL COACHING. LONG-TERM PROGRESS.</p><div className="hero-heading"><h1 id="hero-title">Move better.<br />Build <span className="outline-word">strength.</span></h1><div className="hero-summary"><p>Training built around your body, your goals and the life you want to live.</p><div className="hero-actions"><a className="button" href="#coaching">View plans & prices <span aria-hidden="true">↓</span></a><a className="text-link" href="#contact">Free consultation <span aria-hidden="true">↗</span></a></div></div></div></div>
      <div className="hero-image"><Image src="/force-plate-squat.webp" alt="An athlete completing a jump assessment with coaches at DVOTION" fill priority sizes="(max-width: 800px) 100vw, 94vw" /><div className="image-caption"><span>CHRIS GKOUFAS<br />HEALTH AND PERFORMANCE COACH</span><span className="caption-right">LONDON / ONLINE</span></div></div>
      <div className="hero-foot"><a href="#approach">Explore the approach <span aria-hidden="true">↓</span></a></div>
    </section>
    <section id="approach" className="approach wrap section-space"><div className="section-label"><span>01 / THE APPROACH</span><span>UNDERSTAND. BUILD. ADAPT.</span></div><div className="approach-grid"><h2>Your body sets<br />the starting point.<br /><span className="muted">Your goals set<br />the direction.</span></h2><div className="approach-copy"><p className="lead">Good coaching starts with understanding what problem you are trying to solve.</p><p>I look at your movement options, training history and the demands of your sport or everyday life. Together, we work towards improving relative movement availability, building the capacity to maintain it and building strength without drifting back.</p><p>We review what changes between sessions, adjust the work and keep progressing.</p><a className="text-link" href="https://dvotionlabs.com/about" target="_blank" rel="noreferrer">Explore DVOTION <span aria-hidden="true">↗</span></a></div></div><div className="principles"><div><span>01</span><h3>Understand your movement.</h3><p>Look at the positions you can access and how you organise movement. Use those findings to choose the work.</p></div><div><span>02</span><h3>Build useful strength.</h3><p>Develop strength, power and conditioning that support your goals, at a level you can recover from.</p></div><div><span>03</span><h3>Adapt as you progress.</h3><p>Review your training, your response and your feedback. Adjust the plan as your capacity and life change.</p></div></div></section>
    <section id="coaching" className="coaching-section"><div className="wrap section-space"><div className="section-label"><span>02 / WORK WITH ME</span><span>YOUR TRAINING. YOUR SETTING.</span></div><div className="section-heading"><h2>Coaching that<br />fits your life.</h2><p>The same care and individual attention,<br />wherever you train.<br />Choose a monthly plan or session pack.</p></div><div className="coaching-list">
      <a className="coaching-row" href="/coaching/in-person"><span className="row-number">01</span><div><h3>In person</h3><p>One-to-one strength and movement coaching. Train with me in London.</p></div><span className="row-tag">VIEW PRICING</span><span className="row-arrow" aria-hidden="true">↗</span></a>
      <a className="coaching-row" href="/coaching/virtual"><span className="row-number">02</span><div><h3>Virtual coaching</h3><p>Real-time coaching by video, with guidance and feedback throughout your session. Train from your own gym or home.</p></div><span className="row-tag">VIEW PRICING</span><span className="row-arrow" aria-hidden="true">↗</span></a>
      <a className="coaching-row" href="/coaching/online"><span className="row-number">03</span><div><h3>Online coaching</h3><p>An individual programme to follow in your own time, with regular reviews and adjustments to keep your training moving forward.</p></div><span className="row-tag">VIEW PRICING</span><span className="row-arrow" aria-hidden="true">↗</span></a>
    </div></div></section>
    <section id="chris" className="coach wrap section-space"><div className="coach-image"><Image src="/movement-arm.webp" alt="Chris Gkoufas assessing an athlete’s shoulder movement" fill sizes="(max-width: 760px) 100vw, 48vw" /></div><div className="coach-copy"><p className="eyebrow">03 / YOUR COACH</p><h2>Chris Gkoufas.</h2><p className="coach-role">FOUNDER OF CG PERFORMANCE & DVOTION</p><p className="lead">A considered approach to getting more from your body.</p><p>My work brings together biomechanics, strength and conditioning, and experience coaching professional and recreational athletes.</p><p>Whether you’re working towards an event, returning to consistent training or simply want to feel more capable, I’ll help you build a plan with a clear purpose.</p><div className="credentials"><span>BSc (Hons) Sport & Exercise Science</span><span>Strength & Conditioning Level 4</span><span>UHPC Principles & Concepts Course</span><span>UHPC Assessment Course</span></div><a className="text-link" href="#contact">Tell me what you’re working towards <span aria-hidden="true">↗</span></a></div></section>
    <section className="wrap referral-banner" aria-labelledby="referral-heading"><div><p className="eyebrow">FOR CURRENT CLIENTS</p><h2 id="referral-heading">Refer a friend. Get 50% off a month.</h2><p>When someone you refer joins a monthly Direct Debit plan, you’ll receive 50% off one month of training.</p></div><a className="text-link" href="/referrals">How it works <span aria-hidden="true">↗</span></a></section>
    <section id="contact" className="contact-section"><div className="wrap contact-grid section-space"><div className="contact-copy"><p className="eyebrow">04 / LET’S GET STARTED</p><h2>Your first<br />appointment is free.</h2><p>We’ll discuss your goals, training experience, current lifestyle and any limitations, so I can understand how to help you reach your goals. Leave your details and I’ll be in touch to arrange a time.</p><p className="contact-plan-link"><span>Ready to start?</span><a href="#coaching">View plans & packs <span aria-hidden="true">↗</span></a></p><a className="contact-email" href="mailto:chrisgkoufas.performance@gmail.com">chrisgkoufas.performance@gmail.com ↗</a></div><EnquiryForm consultation /></div></section>
  </>;
}
